# Generated by Django 4.0 on 2024-07-15 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('date_of_event', models.DateTimeField(default=django.utils.timezone.now)),
                ('zoom_url', models.URLField(blank=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
