# Generated by Django 4.0 on 2024-07-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='CalendarEvent',
        ),
    ]
