# Generated by Django 4.0 on 2024-07-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_rename_event_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
