# Generated by Django 4.0 on 2024-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_calendarevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
